kind = "web"
previewPath = "/"
title = "Gamesooty"
version = "1.0.0"
id = "artifacts/gamesooty"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19574

[services.development]
run = "pnpm --filter @workspace/gamesooty run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/gamesooty", "run", "build" ]
serve = "static"
publicDir = "artifacts/gamesooty/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19574"
BASE_PATH = "/"
